import { BookOpen, CheckCircle2, Clock3, Download, FileText, LogOut, Plus, Send, Upload } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import Header from '../components/Header';
import { useAuth } from '../context/AuthContext';
import { API_URL, api } from '../services/api';

const labels = { pending: 'Pending assignment', 'under-review': 'Under review', approved: 'Approved', rejected: 'Rejected', 'revision-requested': 'Revision requested', reviewing: 'Under review', declined: 'Rejected' };
export default function PortalPage() {
  const { user, membership, logout, refresh } = useAuth();
  const navigate = useNavigate();
  const [items, setItems] = useState([]); const [showForm, setShowForm] = useState(false); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ title: '', type: 'journal', abstract: '', manuscript: null });
  const approved = membership?.status === 'approved';
  const load = () => api('/publications/mine').then(result => setItems(result.data)).catch(issue => setError(issue.message));
  useEffect(() => { load(); refresh(); }, []);
  const submit = async event => { event.preventDefault(); setError(''); setSaving(true); try { const body = new FormData(); body.append('title', form.title); body.append('type', form.type); body.append('abstract', form.abstract); body.append('manuscript', form.manuscript); await api('/publications', { method: 'POST', body }); setForm({ title: '', type: 'journal', abstract: '', manuscript: null }); event.target.reset(); setShowForm(false); await load(); } catch (issue) { setError(issue.message); } finally { setSaving(false); } };
  const replace = async (item, file) => { if (!file) return; setError(''); const body = new FormData(); body.append('manuscript', file); try { await api(`/publications/${item._id}/manuscript`, { method: 'PUT', body }); await load(); } catch (issue) { setError(issue.message); } };
  const doLogout = async () => { await logout(); navigate('/'); };
  return <div className="portal-page"><Header light/><main className="portal-shell"><header className="portal-welcome"><div><p className="eyebrow eyebrow--blue">Member portal</p><h1>Welcome, {user.name}</h1><p>{user.email}</p></div><button className="portal-logout" onClick={doLogout}><LogOut/> Sign out</button></header>
    <section className="portal-summary"><article><Clock3/><div><span>Membership</span><strong className={`status-pill status-${membership?.status || 'none'}`}>{membership ? labels[membership.status] || membership.status : 'Not submitted'}</strong></div></article><article><BookOpen/><div><span>Approved work</span><strong>{items.filter(item => item.status === 'approved').length}</strong></div></article><article><FileText/><div><span>In review</span><strong>{items.filter(item => ['pending','under-review'].includes(item.status)).length}</strong></div></article></section>
    {!membership && <section className="portal-callout"><div><h2>Complete your membership application</h2><p>Your account is ready. Submit the application to join the ASMMR member network.</p></div><Link className="button" to="/join">Start application</Link></section>}
    {membership && !approved && <section className="portal-callout"><div><h2>Publication uploads unlock after approval</h2><p>Your membership must be approved before you can submit a journal or research paper.</p></div></section>}
    {membership?.reviewReason && <section className={`review-note status-${membership.status}`}><strong>Membership review note</strong><p>{membership.reviewReason}</p></section>}
    <section className="portal-section"><div className="portal-section-head"><div><h2>Your publications</h2><p>Upload PDFs, track review decisions, and submit improved versions.</p></div><button className="button button--small" disabled={!approved} onClick={() => setShowForm(value => !value)}><Plus/> New submission</button></div>
      {showForm && approved && <form className="publication-form" onSubmit={submit}><label>Title<input value={form.title} onChange={e => setForm({...form,title:e.target.value})} required/></label><label>Type<select value={form.type} onChange={e => setForm({...form,type:e.target.value})}><option value="journal">Journal</option><option value="research-paper">Research paper</option></select></label><label className="wide">Abstract<textarea rows="5" maxLength="3000" value={form.abstract} onChange={e => setForm({...form,abstract:e.target.value})} required/></label><label className="wide">Manuscript PDF <small>(maximum 50 MB)</small><input type="file" accept="application/pdf,.pdf" onChange={e => setForm({...form,manuscript:e.target.files[0] || null})} required/></label><button className="button" disabled={saving}><Send/> {saving ? 'Uploading…' : 'Submit for review'}</button></form>}
      {error && <p className="auth-error">{error}</p>}<div className="submission-list">{items.length ? items.map(item => <article key={item._id}><div className="submission-icon">{item.status === 'approved' ? <CheckCircle2/> : <FileText/>}</div><div><span>{item.type === 'journal' ? 'Journal' : 'Research paper'} · Version {item.version || 1}</span><h3>{item.title}</h3><p>Submitted {new Date(item.createdAt).toLocaleDateString()}{item.fileSize ? ` · ${(item.fileSize / 1024 / 1024).toFixed(1)} MB` : ''}</p>{item.reviewReason && <p className="submission-reason">Reviewer feedback: {item.reviewReason}</p>}<div className="submission-links"><a href={`${API_URL}/publications/${item._id}/manuscript`} target="_blank" rel="noreferrer"><Download/> Download PDF</a>{['rejected','revision-requested'].includes(item.status) && <label className="replace-file"><Upload/> Upload improved PDF<input type="file" accept="application/pdf,.pdf" onChange={e => replace(item, e.target.files[0])}/></label>}</div></div><strong className={`status-pill status-${item.status}`}>{labels[item.status] || item.status}</strong></article>) : <div className="portal-empty"><BookOpen/><h3>No publications submitted yet</h3><p>Your journals and research papers will appear here after membership approval.</p></div>}</div>
    </section></main></div>;
}
